version: '3.4'
services:
  skillchat.server:
    image: '${DOCKER_REGISTRY-}skillchatserver'
    build:
      context: .
      dockerfile: SkillChat.Server/Dockerfile
    volumes:
      - './RavenDB:/app/RavenDB'
      - './Logs:/app/Logs'
    environment:
      - 'ASPNETCORE_URLS=https://+:5001;http://+:5000'
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'
