version: '3.4'
services:
  skillchat.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ASPNETCORE_URLS=https://+:443;http://+:80'
    ports:
      - '80'
      - '443'
      - '8080:5002'
    volumes:
      - '${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro'
